export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const FETCH_HOME = 'FETCH_HOME';
export const FETCH_USER_IMAGES = 'FETCH_USER_IMAGES';
export const FETCH_USER_LIKES = 'FETCH_USER_LIKES';
export const FETCH_IMAGE = 'FETCH_IMAGE';
export const FETCH_IMAGE_USER = 'FETCH_IMAGE_USER';
